"use client"

export default function TermsAndConditions() {
  return (
    <div className="terms-and-conditions bg-[#F3F6FA] w-full h-full p-4 md:p-6 lg:px-14 lg:py-10 xl:px-20 xl:py-16">
      <div className="container mx-auto">
        <div className="terms-and-conditions-content w-full flex flex-col  gap-6 md:gap-8 lg:gap-10 xl:gap-12">
          <div className="content-title">
            <h1 className="text-2xl lg:text-3xl xl:text-4xl font-bold text-[#111827] text-center font-sans">Terms and Conditions</h1>
          </div>
          <div className="content-body flex flex-col gap-4 md:gap-5 lg:gap-6 xl:gap-7 max-w-4xl mx-auto">
            <div className="important-notice bg-yellow-50 border-l-4 border-yellow-400 p-4 md:p-5 rounded">
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#111827] font-sans font-semibold" style={{ lineHeight: '1.6' }}>THIS AGREEMENT CONTAINS AN AGREEMENT TO ARBITRATE ALL CLAIMS (PLEASE SEE SECTION 17). EXCEPT IF YOU OPT-OUT AND EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND QS WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
            </div>

            <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans mt-4 md:mt-6">Table of Contents:</h3>
            <ol className="toc list-decimal list-inside space-y-2 md:space-y-3 text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans ml-4 md:ml-6" style={{ lineHeight: '1.6' }}>
              <li><a href="#modification" className="text-blue-600 hover:text-blue-800 underline">Modification of Terms</a></li>
              <li><a href="#access" className="text-blue-600 hover:text-blue-800 underline">Your Access and Use of the Site</a></li>
              <li><a href="#information" className="text-blue-600 hover:text-blue-800 underline">Information you submit through the Site</a></li>
              <li><a href="#authorization" className="text-blue-600 hover:text-blue-800 underline">Authorization to Obtain a Credit Report and Credit Score</a></li>
              <li><a href="#services" className="text-blue-600 hover:text-blue-800 underline">Services and Content Offered on the Site</a></li>
              <li><a href="#conduct" className="text-blue-600 hover:text-blue-800 underline">Rules of Conduct</a></li>
              <li><a href="#jurisdiction" className="text-blue-600 hover:text-blue-800 underline">Jurisdictional Issues</a></li>
              <li><a href="#links" className="text-blue-600 hover:text-blue-800 underline">Links to third party sites</a></li>
              <li><a href="#registration" className="text-blue-600 hover:text-blue-800 underline">Registration; Usernames and Passwords</a></li>
              <li><a href="#submissions" className="text-blue-600 hover:text-blue-800 underline">Submissions</a></li>
              <li><a href="#rights" className="text-blue-600 hover:text-blue-800 underline">Proprietary Rights</a></li>
              <li><a href="#communications" className="text-blue-600 hover:text-blue-800 underline">Consent to Electronic Communications</a></li>
              <li><a href="#disclaimer" className="text-blue-600 hover:text-blue-800 underline">Disclaimer of Warranties</a></li>
              <li><a href="#liability" className="text-blue-600 hover:text-blue-800 underline">Limitation of Liability</a></li>
              <li><a href="#indemnification" className="text-blue-600 hover:text-blue-800 underline">Indemnification</a></li>
              <li><a href="#release" className="text-blue-600 hover:text-blue-800 underline">Release</a></li>
              <li><a href="#arbitration" className="text-blue-600 hover:text-blue-800 underline">Arbitration</a></li>
              <li><a href="#copyright" className="text-blue-600 hover:text-blue-800 underline">Claims of Copyright Infringement</a></li>
              <li><a href="#governing" className="text-blue-600 hover:text-blue-800 underline">Governing Law</a></li>
            </ol>

            <div className="terms-section mt-6 md:mt-8" id="modification">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Modification of Terms</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>We reserve the right to modify this Agreement from time to time. Your use of the Site after such a modification will constitute your acceptance of those changes. We may notify you of any such changes by any reasonable means, including by posting the revised version of this Agreement to the Site. You can determine when we last changed this Agreement by referring to the &quot;LAST UPDATED&quot; date above.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="access">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Your Access and Use of the Site</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>Your access to and use of the Site may be interrupted from time to time, including due to technical malfunctions, periodic updating and repairs. We may, at any time, modify or discontinue all or part of the Site, charge, modify or waive any fees required to use the Site, or offer opportunities to some or all Site users. We may, in our discretion and without notice, suspend or terminate your access to the Site and to any services offered on the Site, and may remove and delete any content you have provided if we believe that your conduct or content violates or is inconsistent with this Agreement or its intent, that your conduct is disruptive, or that you have violated the law or the rights of any third parties.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="information">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Information you submit through the Site</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>To use certain services on the Site, you may be required to submit information to us, including personally identifying information. Our use and disclosure of any information you submit through the Site is governed by this Agreement and our <a href="privacy_policy.php" className="text-blue-600 hover:text-blue-800 underline">PRIVACY POLICY</a>. You agree that all information you provide to us is true, accurate and complete and that you will not misrepresent your identify, impersonate any third party or enter information on behalf of any third party. You also agree to update such information regularly to keep it current.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="authorization">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Authorization to Obtain a Credit Report and Credit Score</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>You understand and agree that by submitting your request to be matched with lenders, you are providing written instruction under the Fair Credit Reporting Act for our and the lenders with whom you are matched to obtain your consumer credit report, credit score and other information from a consumer reporting agency in order to provide you with quotes and verify your identity. The lenders with whom you are matched may obtain your credit report, credit score and other information to make a final decision regarding extending a loan to you.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="services">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Services and Content Offered on the Site</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>The Site provides you with access to certain services, such as referrals to products, services and service providers that may be of interest to you (the &quot;Site Services&quot;), and to certain content provided by us or by third parties (the &quot;Site Content&quot;). PLEASE READ THE FOLLOWING CAREFULLY:.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>Requests to be Matched. We may provide you with the opportunity to submit requests (each, a &quot;Request&quot;) for information and to be matched with mortgage lenders, personal loan lenders or other service providers (&quot;Service Providers&quot;). A Request is not an application for credit or a request for a loan pre-qualification. Rather, a Request is an inquiry to be matched with Service Providers. The Site acts solely as a paid marketing lead generator. You understand that we are not a broker, lender, creditor for or issuer of the products featured on the Site. We do not make any decisions regarding the products and services offered by the Service Providers and does not make any loan or credit decisions. We are not your agent, nor is it the agent of any Service Provider with respect to your request for financial offerings. Ww may receive a marketing lead generation fee from the Service Providers.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>No guarantee of loan or credit. We cannot and do not guarantee that you will be matched to any Service Provider, that any Service Provider will make a loan or offer to you, or that any program terms including any specific loan terms or rates, offered by the Service Providers are the best terms or lowest rates available in the market. A Service Provider&apos;s offer may be subject to market conditions, approval and qualification. The rates and fees you actually achieve may be higher or lower depending on your complete credit and financial profile. Your ability to secure any loan or consummate any transaction with any Service Provider is solely a matter to be resolved between you and such Service Provider. You may have to complete an application with, and pay an application fee to, the Service Provider before they extend an offer to you or provide that Service Provider with additional information to enable them to further verify your income.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>Transfer of your information. In submitting a Request to us, both we and the Service Providers may ask for your name, Social Security number, address, telephone number, date of birth and other important information to allow us and the Service Providers to verify your identity and match you to offers. In submitting a Request to be matched on the Site, you agree to allow us to transfer all of the information that you provide in connection with your Request to third parties, including Service Providers, whether or not you have specifically selected such Service Provider. If any Service Provider(s) wish to provide information to you in connection with your Request, you will be contacted regarding the offerings and related pricing, and the Service Provider(s) may keep your Request information and any other information provided by us in connection with your Request whether or not they offer you a product or service. Please notify the Service Provider(s) directly if you no longer wish to receive communications from them.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>In submitting a Request to be matched with Service Providers, you further expressly authorize any Service Providers with whom I am matched to share among its affiliates, loan services, and bank partners any transaction history related to your financial products or services received or serviced through such Service Provider for the purpose of evaluating me for credit.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>No endorsements or recommendations. In working with Service Providers, we seek to work with companies that are reputable and professional; however, we strongly recommend that you perform your own due diligence on each potential Service Provider prior to selecting and/or entering into any type of agreement or other arrangement with any particular Service Provider. In addition, once we refer your Request to the Service Providers, We have no further involvement in any transactions that occur between you and the Service Provider(s). We neither recommends nor endorses any specific products, opinions, or other Site Content that may be made available through or mentioned on the Site.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#111827] font-sans font-semibold mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>WE ARE NOT RESPONSIBLE OR LIABLE FOR ANY SERVICE PROVIDER&apos;S ACTS OR OMISSIONS INCLUDING FOR ANY QUOTES OR SERVICES THAT ANY SUCH SERVICE PROVIDER MAY PROVIDE, FOR ANY SERVICE PROVIDER&apos;S CONTACTING OR FAILURE TO CONTACT YOU, FOR ANY SERVICE PROVIDER&apos;S PERFORMANCE OR FAILURE TO PERFORM ANY SERVICES, OR FOR ANY AGREEMENT OR TRANSACTION BETWEEN YOU AND ANY SERVICE PROVIDER.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>No substitute for professional advice. We provide all Site Content and Site Services solely for your convenience, and such Site Content and Site Services (i) are not intended as a substitute for professional advice; (ii) should not be construed as the provision of advice or recommendations; and (iii) should not be relied upon as the basis for any financial decision or action. We are not responsible for the accuracy or reliability of any Site Content or the Site Services. Site Content is not exhaustive and should not be considered complete or up-to-date. It is your responsibility to evaluate the accuracy, completeness or usefulness of any Site Content or Site Services available through the Site. The relationship between you and us is not a professional or similar relationship; always seek the advice of a qualified professional with respect to any questions that you may have, and never disregard professional advice or delay in seeking it because of something that you have read on the Site.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="conduct">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Rules of Conduct</h3>
              <ol className="list-decimal list-inside space-y-2 md:space-y-3 text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans ml-4 md:ml-6 mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>
                <li>You must be at least 18 years old to use the Site.</li>
                <li>You must not post violent, nude, partially nude, discriminatory, unlawful, infringing, hateful, pornographic or sexually suggestive photos or other content via the Site.</li>
                <li>You are responsible for any activity that occurs through your account and you agree you will not sell, transfer, license or assign your account, followers, username, or any account rights. With the exception of people or businesses that are expressly authorized to create accounts on behalf of their employers or clients, we prohibit the creation of and you agree that you will not create an account for anyone other than yourself. You also represent that all information you provide or provided to us upon registration and at all other times will be true, accurate, current and complete and you agree to update your information as necessary to maintain its truth and accuracy.</li>
                <li>You must not create accounts with the Site through unauthorized means, including by using an automated device, script, bot, spider, crawler or scraper.</li>
                <li>You must not solicit, collect or use the login credentials of other Site users.</li>
                <li>You must not use the Site to defame abuse, harass, stalk, threaten or otherwise violate the legal rights of others, including others&apos; privacy rights or rights of publicity, or harvest or collect personally identifiable information about other users of the Site.</li>
                <li>You must not use the Site for any illegal or unauthorized purpose. You agree to comply with all laws, rules and regulations (for example, federal, state, local and provincial) applicable to your use of the Site, including copyright laws.</li>
                <li>You are solely responsible for your conduct and any data, text, files, information, usernames, images, graphics, photos, profiles, audio and video clips, sounds, musical works, works of authorship, applications, links and other content or materials that you submit, post or display on or via the Site.</li>
                <li>You must not interfere or disrupt the Site or servers or networks connected to the Site Services, including by transmitting any worms, viruses, spyware, malware or any other code of a destructive or disruptive nature. You may not inject content or code or otherwise alter or interfere with the way any Site page is rendered or displayed in a user&apos;s browser or device.</li>
                <li>You must not use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, &quot;scrape,&quot; &quot;data mine&quot; or in any way gather Site content or reproduce or circumvent the navigational structure or presentation of the Site without our express prior written consent. Notwithstanding the immediately foregoing sentence (but subject to the other items listed above), we grant the operators of public search engines permission to use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly-available searchable indices of such materials, but not caches or archives of such materials. We reserve the right to revoke these exceptions, either generally or in specific cases, at any time.</li>
                <li>You must not restrict or inhibit any other person from using the Site (including by hacking or defacing any portion of the Site).</li>
                <li>You must not reproduce, duplicate, copy, sell, resell or otherwise exploit for any commercial purposes, any portion of, use of, or access to the Site.</li>
                <li>Except as expressly permitted by applicable law, you must not modify, adapt, translate, reverse engineer, decompile or disassemble any portion of the Site.</li>
                <li>You must not remove any copyright, trademark or other proprietary rights&apos; notices from the Site or materials originating from the Site.</li>
                <li>You must not frame or mirror any part of the Site without our express prior written consent.</li>
                <li>You must not create a database by systematically downloading and storing all or any Site content.</li>
              </ol>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="jurisdiction">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Jurisdictional Issues</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>The Site is controlled and/or operated from the United States, and is not intended to subject us to non-U.S. jurisdiction or laws, except as otherwise expressly stated in this Agreement. The Site may not be appropriate or available for use in some jurisdictions outside of the United States. In choosing to access the Site, you do so on your own initiative and at your own risk, and you are responsible for complying with all local laws, rules and regulations, including any export controls, embargoes or other rules and regulations restricting exports. We may limit the Site&apos;s availability, in whole or in part, to any person, geographic area or jurisdiction we choose, at any time and in our sole discretion.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="links">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Links to third party sites</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>We may provide links to external websites or resources for your convenience and reference only. We do not endorse and is not responsible for the availability of these external websites or resources or for any content, advertising, products, or other materials on or available from such external websites or resources. Your use of and dealings with the owners or operators of these external websites or resources are at your own risk. You cannot make any claim against us, or its Service Providers arising out of your use of external websites or resources..</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="registration">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Registration; Usernames and Passwords</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}> You may be required to register with us in order to access certain services or areas of the Site. With respect to any such registration, we may refuse to grant you, and you may not use, a username (or email address) that violates the intellectual property or other rights of any person; that is offensive; or that we rejects for any other reason in its sole discretion. Your username and password are for your personal use only, and not for use by any other person. You are responsible for maintaining the confidentiality of any password you may use to access the Site, and agree not to transfer your password or username, or lend or otherwise transfer your use of or access to the Site, to any third party. You are fully responsible for all interaction with the Site that occurs in connection with your password or username. You agree to immediately notify us of any unauthorized use of your password or username or any other breach of security related to your account or the Site, and to ensure that you &quot;log off&quot;/exit from your account with the Site (if applicable) at the end of each session. We are not liable for any loss or damage arising from your failure to comply with any of the foregoing obligations.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="submissions">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Submissions</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>For purposes of clarity, you retain ownership of any information, content and/or materials that you submit through the Site (each, a &quot;Submission&quot;). Please note, however, that we need certain rights to your Submissions to be able to make them available on the Site. Accordingly, you hereby grant to us a worldwide, non-exclusive, transferable, sublicenseable (through multiple tiers), royalty-free, perpetual, irrevocable right and license, without compensation to you: to use, reproduce, distribute, adapt (including edit, modify, translate, and reformat), create derivative works of, transmit, publicly display, publicly perform and otherwise exploit such Submission, in any media now known or hereafter developed. For each Submission, you represent and warrant that you have all rights necessary for you to grant the licenses granted in this section, and that such Submission, and your provision thereof to and through the Site, comply with all applicable laws, rules and regulations. Further, to the extent permitted under applicable law, you irrevocably waive any &quot;moral rights&quot; or other rights with respect to attribution of authorship or integrity of materials regarding each Submission that you may have under any applicable law under any legal theory. We requeststhis waiver to help ensure that we have all the rights it may need to provide the Site Services available through the Site. In addition, we have no control over, and shall have no liability for, any damages resulting from the use (including republication) or misuse by any third party of information voluntarily made public through any other part of the Site. IF YOU CHOOSE TO MAKE ANY OF YOUR PERSONALLY IDENTIFIABLE OR OTHER INFORMATION PUBLICLY AVAILABLE IN A SUBMISSION, YOU DO SO AT YOUR OWN RISK. You acknowledge and agree that we reserve the right (but have no obligation) to do any or all of the following, at its sole discretion: (i) monitor, evaluate or alter Submissions before or after they appear on the Site (including through the use of automated filtering software); and (ii) refuse, reject or remove any Submission at any time or for any reason (including through the use of automated filtering software or if we determine, in its sole discretion, that all rights, consents, releases and permissions have not been obtained by you despite your representations above).</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="rights">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Proprietary Rights</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>All of the material included on the Site, including trademarks, text, graphics, logos and service marks, is the property of ours and other parties. U.S. and international copyright laws protects all Site Content available on the Site. Your use of the Site Services and the Site Content does not transfer to you any ownership or other rights in the Site Services or the Site Content. You may download Site Content displayed on the Site for your personal, noncommercial use only, provided you also retain all copyright and other proprietary notices contained on the Site Content. You may not modify, copy, distribute, transmit, display, publish, sell, license, or create derivative works using any of the Site Content for commercial or public purposes.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="communications">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Consent to Electronic Communications</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>When you visit our siteor send email to us, you are communicating with us electronically. You consent to receive communications from us electronically. Although we may choose to communicate with you by regular mail, we may also choose to communicate with you by email or by posting notices on the Site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>
                If you submit a request to be matched with one of our third party lenders, please note that these third party lenders are required by law to provide you with certain communications, notices, disclosures, information and other materials (&quot;Communications&quot;). These third party lenders must obtain your consent in order to provide you with these Communications electronically. By submitting a request to be matched with one of our third party lenders, you affirmatively consent and agree to receive all Communications required under law electronically in accordance with the terms of <a href="/e-sign-consent" className="text-blue-600 hover:text-blue-800 underline">Auto Assuritii E-SIGN CONSENT</a>. PLEASE READ THE TERMS OF THE Auto Assuritii E-SIGN CONSENT CAREFULLY.
              </p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="disclaimer">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Disclaimer of Warranties</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#111827] font-sans font-semibold mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>YOU EXPRESSLY AGREE THAT USE OF THE SITE AND THE SITE SERVICES IS AT YOUR OWN RISK. WE PROVIDE THE SITE AND THE SITE SERVICES ON AN &quot;AS IS&quot; BASIS. WE AND THE SERVICE PROVIDERS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE AND THE SERVICE PROVIDERS MAKE NO WARRANTY THAT THE SITE OR SITE SERVICES WILL MEET YOUR REQUIREMENTS, OR THAT THE SITE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR FREE; NOR DO WE OR THE SERVICE PROVIDERS MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SITE OR SITE SERVICES, AS TO CONFIDENTIALITY OR PRIVACY OF ANY OF USER&apos;S INFORMATION REGISTRATION DATA, EXCEPT AS SET FORTH IN THE SITE&apos;S <a href="privacypolicy.php" className="text-blue-600 hover:text-blue-800 underline">PRIVACY POLICY</a>, OR AS TO THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE SITE OR SITE SERVICES. ANY MATERIAL OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SITE IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA. WE AND THE SERVICE PROVIDERS MAKE NO WARRANTY REGARDING ANY GOODS OR SERVICES PURCHASED OR OBTAINED THROUGH THE SITE OR ANY TRANSACTIONS ENTERED INTO THROUGH THE SITE AND ARE NOT RESPONSIBLE FOR ANY USE OF CONFIDENTIAL OR PRIVATE INFORMATION BY MERCHANTS SELLING THROUGH THE SITE OR OTHER USERS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US, AFFILIATES OR THROUGH THE SITE, SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>While we take commercially reasonable steps to safeguard and to prevent unauthorized access to your information and registration data, we cannot be responsible for the acts of those who gain unauthorized access, and we make no warranty, express, implied, or otherwise, that we will prevent unauthorized access to your private information. IN NO EVENT SHALL WE BE LIABLE FOR ANY DAMAGES (WHETHER CONSEQUENTIAL, DIRECT, INCIDENTAL, INDIRECT, PUNITIVE, SPECIAL OR OTHERWISE) ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, A THIRD PARTY&apos;S UNAUTHORIZED ACCESS TO YOUR INFORMATION OR REGISTRATION DATA, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, STRICT LIABILITY, TORT OR OTHER THEORIES OF LIABILITY, AND ALSO REGARDLESS OF WHETHER WE WERE GIVEN ACTUAL OR CONSTRUCTIVE NOTICE THAT DAMAGES WERE POSSIBLE.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="liability">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Limitation of Liability</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#111827] font-sans font-semibold mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>WE AND THE SERVICE PROVIDERS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES RESULTING FROM THE USE OR THE INABILITY TO USE THE SITE OR FOR COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES OR RESULTING FROM ANY GOODS OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH THE SITE OR RESULTING FROM UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, INCLUDING DAMAGES FOR LOSS OF PROFITS, USE, DATA OR OTHER INTANGIBLE, EVEN IF WE OR THE SERVICE PROVIDERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IN NO EVENT WILL WE AND THE SERVICE PROVIDERS EVER BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES, AND COSTS, WHETHER IN CONTRACT, TORT OR UNDER OTHER FAULT OR WRONGDOING BY WE AND THE SERVICE PROVIDERS OR ANY PERSON FOR WHOM EITHER US OR THE SERVICE PROVIDERS ARE RESPONSIBLE, IN AN AMOUNT EXCEEDING THE AMOUNT YOU PAID TO US FOR THE USE OF THE SITE WHICH IS THE SUBJECT OF THE CLAIM.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="indemnification">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Indemnification</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>You agree to indemnify and hold us, its subsidiaries, affiliates, officers and employees, and Service Providers harmless from any claim or demand, including reasonable attorneys&apos; fees, made by any third party due to or arising out of your use of the Site, the violation of this Agreement by you, or the infringement by you, or other user of the Site using your computer, of any intellectual property or other right of any person or entity. Even though prohibited, people may provide information that is offensive, false, harmful, or deceptive. We and our Service Providers assume no responsibility whatsoever for such content or actions.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="release">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Release</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#111827] font-sans font-semibold mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>YOU HEREBY RELEASE, REMISE AND FOREVER DISCHARGE US AND THE SERVICE PROVIDERS AND EACH OF THEIR RESPECTIVE AGENTS, DIRECTORS, OFFICERS, EMPLOYEES, INFORMATION PROVIDERS, SERVICE PROVIDERS, SUPPLIERS, LICENSORS AND LICENSEES, AND ALL OTHER RELATED, ASSOCIATED, OR CONNECTED PERSONS FROM ANY AND ALL MANNER OF RIGHTS, CLAIMS, COMPLAINTS, DEMANDS, CAUSES OF ACTION, PROCEEDINGS, LIABILITIES, OBLIGATIONS, LEGAL FEES, COSTS, AND DISBURSEMENTS OF ANY NATURE AND KIND WHATSOEVER AND HOWSOEVER ARISING, WHETHER KNOWN OR UNKNOWN, WHICH NOW OR HEREAFTER EXIST, WHICH ARISE FROM, RELATE TO, OR ARE CONNECTED WITH YOUR USE OF THE SITE.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="arbitration">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Arbitration</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#111827] font-sans font-semibold mt-3 md:mt-4" style={{ lineHeight: '1.6' }}><strong>THIS AGREEMENT PROVIDES THAT ALL DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND NOT IN COURT OR BY JURY TRIAL. IF A DISPUTE IS ARBITRATED, YOU GIVE UP YOUR RIGHT TO PARTICIPATE AS A CLASS REPRESENTATIVE OR CLASS MEMBER ON ANY CLASS CLAIM YOU MAY HAVE AGAINST US INCLUDING ANY RIGHT TO CLASS ARBITRATION OR ANY CONSOLIDATION OF INDIVIDUAL ARBITRATIONS. DISCOVERY AND RIGHTS TO APPEAL IN ARBITRATION ARE GENERALLY MORE LIMITED THAN IN A LAWSUIT, AND OTHER RIGHTS AVAILABLE IN COURT MAY NOT BE AVAILABLE IN ARBITRATION.</strong></p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>Except if you opt-out or for disputes relating to: (i) yours or our intellectual property (such as trademarks, trade dress, domain names, trade secrets, copyrights and patents); or (ii) violations of provisions 6.d or 6.i of this Agreement, you agree that all disputes between you and us (whether or not such dispute involves a third party) with regard to your relationship with the Site, including disputes related to this Agreement, your use of the Site, and/or rights of privacy and/or publicity, will be resolved by binding, individual arbitration under the American Arbitration Association&apos;s rules for arbitration of consumer-related disputes and you and us hereby expressly waive trial by jury. As an alternative, you may bring your claim in your local &quot;small claims&quot; court, if permitted by that small claims court&apos;s rules. You may bring claims only on your own behalf. Neither you nor us will participate in a class action or class-wide arbitration for any claims covered by this Agreement. You also agree not to participate in claims brought in a private attorney general or representative capacity, or consolidated claims involving another person&apos;s account, if we is a party to the proceeding. This dispute resolution provision will be governed by the Federal Arbitration Act. In the event the American Arbitration Association is unwilling or unable to set a hearing date within one hundred and sixty (160) days of filing the case, then either us or you can elect to have the arbitration administered instead by the Judicial Arbitration and Mediation Services. Judgment on the award rendered by the arbitrator may be entered in any court having competent jurisdiction. Any provision of applicable law notwithstanding, the arbitrator will not have authority to award damages, remedies or awards that conflict with this Agreement.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>You may opt out of this agreement to arbitrate. If you do so, neither you nor us can require the other to participate in an arbitration proceeding. To opt out, you must notify us in writing within 30 days of the date that you first became subject to this arbitration provision. You must use this address to opt out:</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>
                12540 SW Leveton Dr, #K9224
              </p>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans" style={{ lineHeight: '1.6' }}>
                Tualatin, OR, 97062
              </p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>You must include your name and residence address, the email address you used, and a clear statement that you want to opt out of this arbitration agreement.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>If the prohibition against class actions and other claims brought on behalf of third parties contained above is found to be unenforceable, then all of the preceding language in this Arbitration Clause will be null and void. This arbitration agreement will survive the termination of your relationship with us.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>In any arbitration, we will pay the filing, administration, service or case management fee, plus the costs associated with the first day of arbitration, with the remaining costs to be paid by the non-prevailing party. We will pay additional arbitration expenses to the extent that the arbitrator determines that we must do so in order to ensure the enforceability of this Arbitration Clause. Each party shall be responsible for its own attorney, expert and other fees, unless awarded by the arbitrator under applicable law.</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>The arbitrator&apos;s award is final and binding on all parties, except that the losing party may request a new arbitration under the rules of the arbitration organization by a three-arbitrator panel.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="copyright">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Claims of Copyright Infringement</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>The Digital Millennium Copyright Act of 1998 (the &quot;DMCA&quot;) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that materials available on the Site infringe your copyright, you (or your agent) may send us a notice requesting that we remove the material or block access to it. If you believe in good faith that someone has wrongly filed a notice of copyright infringement against you, the DMCA permits you to send us a counter-notice. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA. See <a href="http://www.copyright.gov/" className="text-blue-600 hover:text-blue-800 underline">http://www.copyright.gov/</a> for details. Notices and counter-notices should be sent to:</p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>
              12540 SW Leveton Dr, #P2150 Tualatin, OR, 97062
              </p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>
                <a href="mailto:contact@assuritii.com" className="text-blue-600 hover:text-blue-800 underline">contact@assuritii.com</a>
              </p>

              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>We suggest that you consult your legal advisor before submitting a notice or counter-notice.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8" id="governing">
              <h3 className="text-xl lg:text-2xl xl:text-3xl font-bold text-[#111827] font-sans">Governing Law</h3>
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans mt-3 md:mt-4" style={{ lineHeight: '1.6' }}>The Agreement shall be governed by and construed in accordance with the laws of the State of Georgia (without regard to conflict of law provisions thereof). If any provision(s) of the Agreement is held contrary to law, then such provision(s) shall be construed, as nearly as possible, to reflect the intentions of the parties with the other provisions remaining in full force and effect. The failure of us to exercise or enforce any right or provision of the Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by us in writing. The section titles in the Agreement are used solely for the convenience of the parties and have no legal or contractual significance.</p>
            </div>

            <div className="terms-section mt-6 md:mt-8">
              <p className="text-sm lg:text-[0.95rem] xl:text-[1.05rem] text-[#374151] font-sans" style={{ lineHeight: '1.6' }}>
                I expressly authorize the third party lender I am matched with to share among its affiliates, loan servicers, and bank partners any transaction history related to my financial products or services received or serviced through the third party lender for the purpose of evaluating me for credit.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
